# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      ANDROID_HOME: /usr/local/android-sdk-linux
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    dependencies:
      pre:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,android-25
        - echo y | android update sdk --no-ui --all --filter build-tools-25.0.2
        - echo y | android update sdk --no-ui --all --filter android-25
        - echo y | android update sdk --no-ui --all --filter tools
        - echo y | android update sdk --no-ui --all --filter extra-android-m2repository
        - echo y | android update sdk --no-ui --all --filter extra-android-support
        - echo y | android update sdk --no-ui --all --filter extra-google-google_play_services
        - echo y | android update sdk --no-ui --all --filter extra-google-m2repository
      override:
          - chmod +x gradlew
          - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test

